### ISSUE TITLE
why the demo code differen form the demo

### ISSUE THREAD

**Issue by GodEngine** [jeka1985/flip-timer#1]
your demo on https://jeka1985.github.io/  was countdown, but the code i clone form your git is increasing timer ... I'm so confusing,how can i make the code as your demo?

BTW your demo is excellent

**Comment by jeka1985** [comment]
Thanks, you can import **Countdown** component and pass Date as **stop** property

`<Countdow stop={new Date("Mon Nov 30 2016 12:36:45 GMT+0300 (MSK)")} />`
