### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by sejsworld** [jeka1985/flip-timer#3]
Hi, 
Looks like a really great component and I would love to use it, but when I run 
Yarn add react-flip-timer 
and import it in my react site like this 
import Countdown from 'react-flip-counter'

And use it as a component in my jsx
<Countdown stop={new Date("Mon Nov 30 2020 00:00:00 GMT+0300 (MSK)")}/>

I get the following error in the browser:

Failed to compile: 
launch/node_modules/react-flip-counter/src/Countdown/index.js Unexpected token (82:11)
You may need an appropriate loader to handle this file type.
|     };
| 
|     return <div className={cn(st.countdown, this.props.className)}>
|       {Object.keys(this.state.diff).map(key => <div
|         key={key}

Am I missing something? 
Thank you in advance
Steffen

**Comment by jeka1985** [comment]
Hi Steffen, 

No, its my bad( 

You faced common problem, looks like you exclude node_modules from babel loader, as well as any css preprocessors.

Unfortunately, as a lack of time,  i have not yet implement solution to import component with its resources into client code.

Hope following workaround will work for you:

- clone (or download arhive) github repo
- drop Countdown component into you components folder
- use as local component

Regards,
Eugene

**Comment by sejsworld** [comment]
We didnt succes due to the styling and classes. Can see that this has been updated, are there any chance to fix the issue

**Comment by jeka1985** [comment]
Yes, please up to 0.4.0 and follow webpack instuctions
